Repository innercicle-be-rate-limiter/rate-limiter-spring-boot-starter, pull requests merged in 2024-12, with the labels that each got.

#9 Rate-type token-bucket 아닐 경우Handler 중복 등록 이슈 해결
  rate-limiter-spring-boot-autoconfigure/src/main/java/com/innercicle/RateLimiterAutoConfiguration.java
Labels: 🐞 Bug

#12 fix : 버전 업 이슈 수정
  .github/workflows/github-actions.yml
Labels: 🐞 Bug, 🌏 Deploy

#13 fix : github action version up 방식 수정
  .github/workflows/github-actions.yml
Labels: 🐞 Bug

#14 fix : github action version up
  .github/workflows/github-actions.yml
Labels: 🐞 Bug, 🌏 Deploy

#15 fix : github-actions version up
  .github/workflows/github-actions.yml
Labels: 🐞 Bug

#17 Update github-actions.yml
  .github/workflows/github-actions.yml
Labels: 🐞 Bug

#18 fix : release 방식 수정
  .github/workflows/github-actions.yml
Labels: 🐞 Bug, 🌏 Deploy

#19 refactor: pure 레벨로 디펜던시 낮춤
  rate-limiter-spring-boot-autoconfigure/build.gradle
  rate-limiter-spring-boot-autoconfigure/src/main/java/com/innercicle/RateLimiterAutoConfiguration.java
  rate-limiter/build.gradle
  rate-limiter/src/main/java/com/innercicle/aop/RateLimitAop.java
  rate-limiter/src/main/java/com/innercicle/cache/BucketRedisTemplate.java
  rate-limiter/src/main/java/com/innercicle/domain/AbstractTokenInfo.java
Labels: ⬆️ enhancement, 🌏 Deploy

#24 feat: example 폴더 추가
  example/build.gradle
  example/src/main/java/com/innercircle/ExampleApplication.java
  example/src/main/java/com/innercircle/controller/ParkingV1Controller.java
  example/src/main/java/com/innercircle/controller/request/ParkingApplyRequest.java
  example/src/main/java/com/innercircle/controller/response/ParkingApplyResponse.java
  example/src/main/java/com/innercircle/domain/CarInfo.java
  example/src/main/java/com/innercircle/entity/CarEntity.java
  example/src/main/java/com/innercircle/entity/EntitySequence.java
  example/src/main/java/com/innercircle/entity/IdGenerator.java
  example/src/main/java/com/innercircle/repository/ParkingRepository.java
  example/src/main/java/com/innercircle/service/ParkingService.java
  example/src/main/java/com/innercircle/service/RateLimitingService.java
  example/src/main/resources/application.yml
  example/src/test/java/com/innercircle/ExampleApplicationTest.java
  example/src/test/java/com/innercircle/container/PostgresTestContainerInitializer.java
  example/src/test/java/com/innercircle/container/RedisTestContainer.java
  example/src/test/java/com/innercircle/service/ParkingServiceTokenBucketTest.java
  example/src/test/java/com/innercircle/service/SlidingWindowLoggingTest.java
  example/src/test/resources/application-test.yml
  rate-limiter-spring-boot-autoconfigure/src/main/java/com/innercicle/RateLimiterAutoConfiguration.java
  rate-limiter/src/main/java/com/innercicle/cache/BucketRedisTemplate.java
  rate-limiter/src/main/java/com/innercicle/cache/CacheTemplate.java
  rate-limiter/src/main/java/com/innercicle/domain/AbstractTokenInfo.java
  rate-limiter/src/main/java/com/innercicle/domain/BucketProperties.java
  rate-limiter/src/main/java/com/innercicle/domain/FixedWindowCountInfo.java
  rate-limiter/src/main/java/com/innercicle/domain/SlidingWindowLogging.java
  rate-limiter/src/main/java/com/innercicle/domain/SlidingWindowLoggingInfo.java
  rate-limiter/src/main/java/com/innercicle/handler/FixedWindowCounterHandler.java
  rate-limiter/src/main/java/com/innercicle/handler/SlidingWindowLoggingHandler.java
  settings.gradle
Labels: ⬆️ enhancement
